// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface SbButton {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  type?: "" | "brand-orange" | "cream" | "strategy-gold" | "strategy-green" | "strategy-red" | "strategy-charcoal";
  variant?: "" | "primary" | "outline";
  showArrowIcon?: boolean;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface SbPage {
  body?: (SbButton | SbPage | SbTeaser | SbVideoHero)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SbTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface SbVideoHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  background_video?: StoryblokAsset;
  fallback_image: StoryblokAsset;
  component: "videoHero";
  _uid: string;
  [k: string]: unknown;
}
