// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext, StoryblokAsset, StoryblokMultilink, StoryblokTable } from '../storyblok.d.ts';
export interface SbBadge {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  backgroundColor?: number | string;
  textColor?: number | string;
  component: "badge";
  _uid: string;
  [k: string]: unknown;
}

export interface SbButton {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  type?: "brand-orange" | "cream" | "strategy-gold" | "strategy-green" | "strategy-red" | "strategy-charcoal";
  variant?: "" | "primary" | "outline";
  size?: "" | "small" | "medium" | "large";
  showArrowIcon?: boolean;
  tailwindClasses?: string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface SbCard {
  title: string;
  content: StoryblokRichtext;
  backgroundColor: number | string;
  titleColor?: number | string;
  textColor?: number | string;
  component: "card";
  _uid: string;
  [k: string]: unknown;
}

export interface SbContent {
  content?: StoryblokRichtext;
  color?: number | string;
  backgroundColor?: number | string;
  component: "content";
  _uid: string;
  [k: string]: unknown;
}

export interface SbDonation {
  subtitle: string;
  title: string;
  description?: StoryblokRichtext;
  badges?: SbBadge[];
  options: ("" | "5" | "10" | "25" | "50" | "100" | "150" | "200" | "250" | "300" | "350" | "400" | "450" | "500")[];
  preselected: string;
  defaultFrequency?: "" | "once" | "monthly";
  funds?: StoryblokTable;
  backgroundColor?: number | string;
  primaryColor?: number | string;
  secondaryColor?: number | string;
  textColor?: number | string;
  component: "donation";
  _uid: string;
  [k: string]: unknown;
}

export interface SbEvent {
  title: string;
  description: string;
  date: string;
  speaker?: string;
  location?: string;
  thumbnail?: StoryblokAsset;
  type?: "" | "service" | "event";
  pillar: number | string;
  component: "event";
  _uid: string;
  [k: string]: unknown;
}

export interface SbFooter {
  title: string;
  information?: (SbInformationItem | SbButton)[];
  image: StoryblokAsset;
  copyright: string;
  links?: SbLink[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface SbFullGrid {
  columns?: (
    | SbBadge
    | SbButton
    | SbCard
    | SbContent
    | SbDonation
    | SbEvent
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbScripture
    | SbScrollingText
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  backgroundColor: number | string;
  component: "fullGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbGlobal {
  item: (SbFooter | SbNavigation)[];
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface SbGrid {
  columns?: (
    | SbBadge
    | SbButton
    | SbCard
    | SbContent
    | SbDonation
    | SbEvent
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbScripture
    | SbScrollingText
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  backgroundColor: number | string;
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbImage {
  image: StoryblokAsset;
  fullHeight?: boolean;
  objectFit?: "" | "cover" | "contain" | "fill" | "none" | "scale-down";
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface SbImageCard {
  title: string;
  description: string;
  image?: StoryblokAsset;
  actions?: (SbButton | SbLink)[];
  textColor?: number | string;
  component: "imageCard";
  _uid: string;
  [k: string]: unknown;
}

export interface SbImageHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  image: StoryblokAsset;
  component: "imageHero";
  _uid: string;
  [k: string]: unknown;
}

export interface SbInformationItem {
  title: string;
  text: string;
  component: "informationItem";
  _uid: string;
  [k: string]: unknown;
}

export interface SbLink {
  text: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  textColor?: number | string;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface SbPage {
  logo: StoryblokAsset;
  cta?: SbButton[];
  body?: (
    | SbBadge
    | SbButton
    | SbCard
    | SbContent
    | SbDonation
    | SbEvent
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbScripture
    | SbScrollingText
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  global_footer?: (ISbStoryData<sbGlobal> | string)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SbPersonCard {
  image: StoryblokAsset;
  name: string;
  role?: string;
  backgroundColor?: number | string;
  textColor?: number | string;
  component: "personCard";
  _uid: string;
  [k: string]: unknown;
}

export interface SbScripture {
  badge?: string;
  scripture: string;
  reference: string;
  backgroundColor: number | string;
  textColor?: number | string;
  component: "scripture";
  _uid: string;
  [k: string]: unknown;
}

export interface SbScrollingText {
  text?: string;
  backgroundColor?: number | string;
  textColor?: number | string;
  component: "scrollingText";
  _uid: string;
  [k: string]: unknown;
}

export interface SbStaticGrid {
  items: (
    | SbBadge
    | SbButton
    | SbCard
    | SbContent
    | SbDonation
    | SbEvent
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbScripture
    | SbScrollingText
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  backgroundColor?: number | string;
  component: "staticGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface SbVideoHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  background_video?: StoryblokAsset;
  fallback_image: StoryblokAsset;
  component: "videoHero";
  _uid: string;
  [k: string]: unknown;
}
