// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokRichtext, StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface SbBadge {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "badge";
  _uid: string;
  [k: string]: unknown;
}

export interface SbButton {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  type?: "brand-orange" | "cream" | "strategy-gold" | "strategy-green" | "strategy-red" | "strategy-charcoal";
  variant?: "" | "primary" | "outline";
  showArrowIcon?: boolean;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface SbContent {
  content?: StoryblokRichtext;
  component: "content";
  _uid: string;
  [k: string]: unknown;
}

export interface SbGrid {
  columns?: (SbBadge | SbButton | SbContent | SbGrid | SbPage | SbScripture | SbTeaser | SbVideoHero)[];
  backgroundColor: number | string;
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbPage {
  body?: (SbBadge | SbButton | SbContent | SbGrid | SbPage | SbScripture | SbTeaser | SbVideoHero)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SbScripture {
  badge?: string;
  scripture: string;
  reference: string;
  backgroundColor?: number | string;
  component: "scripture";
  _uid: string;
  [k: string]: unknown;
}

export interface SbTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface SbVideoHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  background_video?: StoryblokAsset;
  fallback_image: StoryblokAsset;
  component: "videoHero";
  _uid: string;
  [k: string]: unknown;
}
