// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js'
import type {
  StoryblokRichtext,
  StoryblokMultilink,
  StoryblokAsset,
} from '../storyblok.d.ts'
export interface SbAnimatedMap {
  animated?: boolean
  component: 'animatedMap'
  _uid: string
  [k: string]: unknown
}

export interface SbBadge {
  text: string
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  backgroundColor?: number | string
  textColor?: number | string
  component: 'badge'
  _uid: string
  [k: string]: unknown
}

export interface SbBigCard {
  title: string
  description: string
  image: StoryblokAsset
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  component: 'bigCard'
  _uid: string
  [k: string]: unknown
}

export interface SbBlokHero {
  title: string
  subtitle: string
  buttons?: SbButton[]
  block?: (
    | SbAnimatedMap
    | SbBadge
    | SbBigCard
    | SbBlokHero
    | SbButton
    | SbCard
    | SbCarousel
    | SbDonation
    | SbEvent
    | SbEventHighlight
    | SbEventList
    | SbFaq
    | SbFaqItem
    | SbFeature
    | SbFilloutForm
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbMap
    | SbMenuItem
    | SbMenuSection
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSection
    | SbSermon
    | SbSermonHighlight
    | SbSocialLink
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbTeaser
    | SbTestimony
    | SbTestimonyCarousel
    | SbVideoHero
    | SbWebsiteConfig
  )[]
  image: StoryblokAsset
  component: 'blokHero'
  _uid: string
  [k: string]: unknown
}

export interface SbButton {
  text: string
  link?: Exclude<StoryblokMultilink, { linktype?: 'email' }>
  type:
    | 'brand-orange'
    | 'cream'
    | 'strategy-gold'
    | 'strategy-green'
    | 'strategy-red'
    | 'strategy-charcoal'
  variant?: '' | 'primary' | 'outline'
  size?: '' | 'small' | 'medium' | 'large'
  showArrowIcon?: boolean
  tailwindClasses?: string
  component: 'button'
  _uid: string
  [k: string]: unknown
}

export interface SbCard {
  title: string
  content: StoryblokRichtext
  backgroundColor: number | string
  titleColor?: number | string
  textColor?: number | string
  component: 'card'
  _uid: string
  [k: string]: unknown
}

export interface SbCarousel {
  dots?: boolean
  infinite?: boolean
  navigation?: boolean
  speed?: string
  slidesToShow?: string
  slidesToScroll?: string
  centerMode?: boolean
  swipeToSlide?: boolean
  draggable?: boolean
  arrows?: boolean
  bloks?: (SbBigCard | SbCard | SbImage | SbImageCard | SbPersonCard)[]
  autplay?: boolean
  autoplayInterval?: string
  component: 'carousel'
  _uid: string
  [k: string]: unknown
}

export interface SbDonation {
  subtitle: string
  title: string
  description?: StoryblokRichtext
  options: (
    | ''
    | '5'
    | '10'
    | '25'
    | '50'
    | '100'
    | '150'
    | '200'
    | '250'
    | '300'
    | '350'
    | '400'
    | '450'
    | '500'
  )[]
  preselected: string
  defaultFrequency: '' | 'oneTime' | 'monthly'
  purposes?: string[]
  backgroundColor?: number | string
  primaryColor?: number | string
  textColor?: number | string
  component: 'donation'
  _uid: string
  [k: string]: unknown
}

export interface SbEvent {
  title: string
  description: string
  date: string
  speaker?: string
  location?: string
  thumbnail?: StoryblokAsset
  video?: StoryblokAsset
  type?: 'service' | 'event' | 'youth' | 'teens' | 'disciples' | 'prayer'
  language: '' | 'Nederlands' | 'Engels'
  translationAvailable?: boolean
  preacherPicture?: StoryblokAsset
  youtubeLink?: Exclude<
    StoryblokMultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  component: 'event'
  _uid: string
  [k: string]: unknown
}

export interface SbEventHighlight {
  title: string
  description?: string
  button?: SbButton[]
  events?: (ISbStoryData<sbEvent> | string)[]
  filterByType?: number | string
  component: 'eventHighlight'
  _uid: string
  [k: string]: unknown
}

export interface SbEventList {
  title: string
  backgroundColor: number | string
  textColor: number | string
  showStoryScroll?: boolean
  component: 'eventList'
  _uid: string
  [k: string]: unknown
}

export interface SbFaq {
  title?: string
  subtitle?: string
  items: SbFaqItem[]
  backgroundColor?: number | string
  component: 'faq'
  _uid: string
  [k: string]: unknown
}

export interface SbFaqItem {
  question: string
  answer: StoryblokRichtext
  component: 'faqItem'
  _uid: string
  [k: string]: unknown
}

export interface SbFeature {
  name?: string
  component: 'feature'
  _uid: string
  [k: string]: unknown
}

export interface SbFilloutForm {
  id: string
  type?: 'standard' | 'fullscreen' | 'popup' | 'slider'
  buttonText?: string
  buttonColor?: number | string
  component: 'filloutForm'
  _uid: string
  [k: string]: unknown
}

export interface SbFooter {
  title: string
  information?: (SbInformationItem | SbButton)[]
  image: StoryblokAsset
  copyright: string
  links?: SbLink[]
  component: 'footer'
  _uid: string
  [k: string]: unknown
}

export interface SbFullGrid {
  columns?: (
    | SbAnimatedMap
    | SbBadge
    | SbBigCard
    | SbBlokHero
    | SbButton
    | SbCard
    | SbCarousel
    | SbDonation
    | SbEvent
    | SbEventHighlight
    | SbEventList
    | SbFaq
    | SbFaqItem
    | SbFeature
    | SbFilloutForm
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbMap
    | SbMenuItem
    | SbMenuSection
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSection
    | SbSermon
    | SbSermonHighlight
    | SbSocialLink
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbTeaser
    | SbTestimony
    | SbTestimonyCarousel
    | SbVideoHero
    | SbWebsiteConfig
  )[]
  backgroundColor: number | string
  component: 'fullGrid'
  _uid: string
  [k: string]: unknown
}

export interface SbGlobal {
  item: SbFooter[]
  component: 'global'
  _uid: string
  [k: string]: unknown
}

export interface SbGrid {
  columns?: (
    | SbAnimatedMap
    | SbBadge
    | SbBigCard
    | SbBlokHero
    | SbButton
    | SbCard
    | SbCarousel
    | SbDonation
    | SbEvent
    | SbEventHighlight
    | SbEventList
    | SbFaq
    | SbFaqItem
    | SbFeature
    | SbFilloutForm
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbMap
    | SbMenuItem
    | SbMenuSection
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSection
    | SbSermon
    | SbSermonHighlight
    | SbSocialLink
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbTeaser
    | SbTestimony
    | SbTestimonyCarousel
    | SbVideoHero
    | SbWebsiteConfig
  )[]
  backgroundColor: number | string
  component: 'grid'
  _uid: string
  [k: string]: unknown
}

export interface SbImage {
  image: StoryblokAsset
  animated?: boolean
  objectFit?: '' | 'cover' | 'contain' | 'fill' | 'none' | 'scale-down'
  side?: '' | 'left' | 'right'
  delay?: string
  priority?: boolean
  loading?: '' | 'lazy' | 'eager'
  component: 'image'
  _uid: string
  [k: string]: unknown
}

export interface SbImageCard {
  title: string
  description: string
  image?: StoryblokAsset
  actions?: (SbButton | SbLink)[]
  textColor?: number | string
  backgroundColor: number | string
  component: 'imageCard'
  _uid: string
  [k: string]: unknown
}

export interface SbImageHero {
  title: string
  subtitle: string
  buttons?: (SbButton | SbFilloutForm)[]
  image: StoryblokAsset
  component: 'imageHero'
  _uid: string
  [k: string]: unknown
}

export interface SbInformationItem {
  title: string
  text: string
  component: 'informationItem'
  _uid: string
  [k: string]: unknown
}

export interface SbLink {
  text: string
  link: Exclude<StoryblokMultilink, { linktype?: 'asset' }>
  textColor?: number | string
  component: 'link'
  _uid: string
  [k: string]: unknown
}

export interface SbMap {
  latitude: string
  longitude: string
  zoom: string
  geojson?: string
  component: 'map'
  _uid: string
  [k: string]: unknown
}

export interface SbMenuItem {
  label: string
  link: Exclude<
    StoryblokMultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  open_in_new_tab?: boolean
  component: 'menuItem'
  _uid: string
  [k: string]: unknown
}

export interface SbMenuSection {
  title: string
  items: SbMenuItem[]
  component: 'menuSection'
  _uid: string
  [k: string]: unknown
}

export interface SbPage {
  seo?: unknown
  body?: (
    | SbBlokHero
    | SbEventHighlight
    | SbEventList
    | SbFaq
    | SbFullGrid
    | SbGrid
    | SbImageHero
    | SbScrollingText
    | SbSection
    | SbTeaser
    | SbVideoHero
  )[]
  index?: boolean
  follow?: boolean
  backgroundColor?: number | string
  component: 'page'
  _uid: string
  [k: string]: unknown
}

export interface SbPersonCard {
  image: StoryblokAsset
  name: string
  role?: string
  backgroundColor?: number | string
  textColor?: number | string
  about?: StoryblokRichtext
  component: 'personCard'
  _uid: string
  [k: string]: unknown
}

export interface SbRichText {
  content?: StoryblokRichtext
  color?: number | string
  component: 'richText'
  _uid: string
  [k: string]: unknown
}

export interface SbScripture {
  badge?: string
  scripture: string
  reference: string
  textColor?: number | string
  component: 'scripture'
  _uid: string
  [k: string]: unknown
}

export interface SbScriptureReferences {
  scriptures: SbStatementScripture[]
  component: 'scriptureReferences'
  _uid: string
  [k: string]: unknown
}

export interface SbScrollingText {
  text?: string
  backgroundColor?: number | string
  textColor?: number | string
  component: 'scrollingText'
  _uid: string
  [k: string]: unknown
}

export interface SbSection {
  block?: (
    | SbAnimatedMap
    | SbBadge
    | SbBigCard
    | SbBlokHero
    | SbButton
    | SbCard
    | SbCarousel
    | SbDonation
    | SbEvent
    | SbEventHighlight
    | SbEventList
    | SbFaq
    | SbFaqItem
    | SbFeature
    | SbFilloutForm
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbMap
    | SbMenuItem
    | SbMenuSection
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSection
    | SbSermon
    | SbSermonHighlight
    | SbSocialLink
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbTeaser
    | SbTestimony
    | SbTestimonyCarousel
    | SbVideoHero
    | SbWebsiteConfig
  )[]
  backgroundColor?: number | string
  component: 'section'
  _uid: string
  [k: string]: unknown
}

export interface SbSermon {
  title: string
  speaker: string
  date: string
  duration?: string
  thumbnail: StoryblokAsset
  youtubeUrl: Exclude<
    StoryblokMultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  series?: string
  language?: '' | 'Nederlands' | 'Engels'
  translationAvailable?: boolean
  component: 'sermon'
  _uid: string
  [k: string]: unknown
}

export interface SbSermonHighlight {
  title: string
  speaker: string
  date: string
  duration?: string
  thumbnail: StoryblokAsset
  youtubeUrl: Exclude<
    StoryblokMultilink,
    { linktype?: 'email' } | { linktype?: 'asset' }
  >
  series?: string
  language?: '' | 'Nederlands' | 'Engels'
  translationAvailable?: boolean
  primaryColor?: number | string
  secondaryColor?: number | string
  component: 'sermonHighlight'
  _uid: string
  [k: string]: unknown
}

export interface SbSocialLink {
  label: string
  url: string
  component: 'socialLink'
  _uid: string
  [k: string]: unknown
}

export interface SbSpotifyEmbed {
  spotifyUrl: string
  component: 'spotifyEmbed'
  _uid: string
  [k: string]: unknown
}

export interface SbStatement {
  subtitle: string
  statement: string
  explanation: string
  scriptures?: SbScriptureReferences[]
  component: 'statement'
  _uid: string
  [k: string]: unknown
}

export interface SbStatementScripture {
  ref?: string
  content?: string
  component: 'statementScripture'
  _uid: string
  [k: string]: unknown
}

export interface SbTeaser {
  headline?: string
  component: 'teaser'
  _uid: string
  [k: string]: unknown
}

export interface SbTestimony {
  name: string
  designation: string
  quote: string
  image: StoryblokAsset
  component: 'testimony'
  _uid: string
  [k: string]: unknown
}

export interface SbTestimonyCarousel {
  title?: string
  testimonials: SbTestimony[]
  autplay?: boolean
  textColor?: number | string
  component: 'testimonyCarousel'
  _uid: string
  [k: string]: unknown
}

export interface SbVideoHero {
  title: string
  subtitle: string
  buttons?: SbButton[]
  background_video?: StoryblokAsset
  fallback_image: StoryblokAsset
  component: 'videoHero'
  _uid: string
  [k: string]: unknown
}

export interface SbWebsiteConfig {
  footer_logo?: StoryblokAsset
  footer_description: string
  footer_menu?: SbMenuSection[]
  footer_tagline: string
  site_name: string
  logo: StoryblokAsset
  logo_alt: string
  show_menu?: boolean
  header_cta_buttons?: SbButton[]
  menu_data?: SbMenuSection[]
  social_links?: SbSocialLink[]
  component: 'websiteConfig'
  _uid: string
  [k: string]: unknown
}
