// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext } from '../storyblok.d.ts';
export interface SbBadge {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  backgroundColor?: number | string;
  textColor?: number | string;
  component: "badge";
  _uid: string;
  [k: string]: unknown;
}

export interface SbBlokHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  block?: (
    | SbBadge
    | SbBlokHero
    | SbButton
    | SbCard
    | SbDonation
    | SbEvent
    | SbFeature
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSermon
    | SbSermonHighlight
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  image: StoryblokAsset;
  component: "blokHero";
  _uid: string;
  [k: string]: unknown;
}

export interface SbButton {
  text: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  type?: "brand-orange" | "cream" | "strategy-gold" | "strategy-green" | "strategy-red" | "strategy-charcoal";
  variant?: "" | "primary" | "outline";
  size?: "" | "small" | "medium" | "large";
  showArrowIcon?: boolean;
  tailwindClasses?: string;
  component: "button";
  _uid: string;
  [k: string]: unknown;
}

export interface SbCard {
  title: string;
  content: StoryblokRichtext;
  backgroundColor: number | string;
  titleColor?: number | string;
  textColor?: number | string;
  component: "card";
  _uid: string;
  [k: string]: unknown;
}

export interface SbDonation {
  subtitle: string;
  title: string;
  description?: StoryblokRichtext;
  options: ("" | "5" | "10" | "25" | "50" | "100" | "150" | "200" | "250" | "300" | "350" | "400" | "450" | "500")[];
  preselected: string;
  defaultFrequency: "" | "oneTime" | "monthly";
  backgroundColor?: number | string;
  primaryColor?: number | string;
  textColor?: number | string;
  component: "donation";
  _uid: string;
  [k: string]: unknown;
}

export interface SbEvent {
  title: string;
  description: string;
  date: string;
  speaker?: string;
  location?: string;
  thumbnail?: StoryblokAsset;
  type?: "" | "service" | "event";
  language: "" | "Nederlands" | "Engels";
  translationAvailable?: boolean;
  component: "event";
  _uid: string;
  [k: string]: unknown;
}

export interface SbFeature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface SbFooter {
  title: string;
  information?: (SbInformationItem | SbButton)[];
  image: StoryblokAsset;
  copyright: string;
  links?: SbLink[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface SbFullGrid {
  columns?: (
    | SbBadge
    | SbBlokHero
    | SbButton
    | SbCard
    | SbDonation
    | SbEvent
    | SbFeature
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSermon
    | SbSermonHighlight
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  backgroundColor: number | string;
  component: "fullGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbGlobal {
  item: SbFooter[];
  component: "global";
  _uid: string;
  [k: string]: unknown;
}

export interface SbGrid {
  columns?: (
    | SbBadge
    | SbBlokHero
    | SbButton
    | SbCard
    | SbDonation
    | SbEvent
    | SbFeature
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSermon
    | SbSermonHighlight
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  backgroundColor: number | string;
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbImage {
  image: StoryblokAsset;
  fullHeight?: boolean;
  objectFit?: "" | "cover" | "contain" | "fill" | "none" | "scale-down";
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface SbImageCard {
  title: string;
  description: string;
  image?: StoryblokAsset;
  actions?: (SbButton | SbLink)[];
  textColor?: number | string;
  component: "imageCard";
  _uid: string;
  [k: string]: unknown;
}

export interface SbImageHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  image: StoryblokAsset;
  component: "imageHero";
  _uid: string;
  [k: string]: unknown;
}

export interface SbInformationItem {
  title: string;
  text: string;
  component: "informationItem";
  _uid: string;
  [k: string]: unknown;
}

export interface SbLink {
  text: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  textColor?: number | string;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface SbPage {
  seo?: unknown;
  logo: StoryblokAsset;
  cta?: SbButton[];
  body?: (
    | SbBadge
    | SbBlokHero
    | SbButton
    | SbCard
    | SbDonation
    | SbEvent
    | SbFeature
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSermon
    | SbSermonHighlight
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  global_footer?: (ISbStoryData<sbGlobal> | string)[];
  index?: boolean;
  follow?: boolean;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface SbPersonCard {
  image: StoryblokAsset;
  name: string;
  role?: string;
  backgroundColor?: number | string;
  textColor?: number | string;
  component: "personCard";
  _uid: string;
  [k: string]: unknown;
}

export interface SbRichText {
  content?: StoryblokRichtext;
  color?: number | string;
  backgroundColor?: number | string;
  containerized?: boolean;
  component: "richText";
  _uid: string;
  [k: string]: unknown;
}

export interface SbScripture {
  badge?: string;
  scripture: string;
  reference: string;
  backgroundColor: number | string;
  textColor?: number | string;
  component: "scripture";
  _uid: string;
  [k: string]: unknown;
}

export interface SbScriptureReferences {
  scriptures: SbStatementScripture[];
  component: "scriptureReferences";
  _uid: string;
  [k: string]: unknown;
}

export interface SbScrollingText {
  text?: string;
  backgroundColor?: number | string;
  textColor?: number | string;
  component: "scrollingText";
  _uid: string;
  [k: string]: unknown;
}

export interface SbSermon {
  title: string;
  speaker: string;
  date: string;
  duration?: string;
  thumbnail: StoryblokAsset;
  youtubeUrl: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  series?: string;
  language?: "" | "Nederlands" | "Engels";
  translationAvailable?: boolean;
  component: "sermon";
  _uid: string;
  [k: string]: unknown;
}

export interface SbSermonHighlight {
  title: string;
  speaker: string;
  date: string;
  duration?: string;
  thumbnail: StoryblokAsset;
  youtubeUrl: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  series?: string;
  language?: "" | "Nederlands" | "Engels";
  translationAvailable?: boolean;
  backgroundColor?: number | string;
  primaryColor?: number | string;
  secondaryColor?: number | string;
  component: "sermonHighlight";
  _uid: string;
  [k: string]: unknown;
}

export interface SbSpotifyEmbed {
  spotifyUrl: string;
  component: "spotifyEmbed";
  _uid: string;
  [k: string]: unknown;
}

export interface SbStatement {
  subtitle: string;
  statement: string;
  explanation: string;
  scriptures?: SbScriptureReferences[];
  backgroundColor?: number | string;
  component: "statement";
  _uid: string;
  [k: string]: unknown;
}

export interface SbStatementScripture {
  ref?: string;
  content?: string;
  component: "statementScripture";
  _uid: string;
  [k: string]: unknown;
}

export interface SbStaticGrid {
  items: (
    | SbBadge
    | SbBlokHero
    | SbButton
    | SbCard
    | SbDonation
    | SbEvent
    | SbFeature
    | SbFooter
    | SbFullGrid
    | SbGlobal
    | SbGrid
    | SbImage
    | SbImageCard
    | SbImageHero
    | SbInformationItem
    | SbLink
    | SbPage
    | SbPersonCard
    | SbRichText
    | SbScripture
    | SbScriptureReferences
    | SbScrollingText
    | SbSermon
    | SbSermonHighlight
    | SbSpotifyEmbed
    | SbStatement
    | SbStatementScripture
    | SbStaticGrid
    | SbTeaser
    | SbVideoHero
  )[];
  backgroundColor?: number | string;
  component: "staticGrid";
  _uid: string;
  [k: string]: unknown;
}

export interface SbTeaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export interface SbVideoHero {
  title: string;
  subtitle: string;
  buttons?: SbButton[];
  background_video?: StoryblokAsset;
  fallback_image: StoryblokAsset;
  component: "videoHero";
  _uid: string;
  [k: string]: unknown;
}
